export const locations = [
    
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  
    // Union Territories
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
  
    // Major IT Hubs
    "Bangalore",
    "Hyderabad",
    "Mumbai",
    "Pune",
    "Gurgaon",
    "Noida",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Coimbatore",
    "Thiruvananthapuram",
    "Kochi",
    "Bhubaneswar",
    "Indore",
    "Jaipur",
    "Visakhapatnam",
    "Nagpur",
    "Lucknow",
    "Bhopal",
    "Surat"
  ];